<div class="row">
    <div class="col-md-6">
        <h3>Comments</h3>
        <?php if (Authentication::isLoggedOn()) : ?>
            <div class="comment-box row p-2 m-0 mr-auto">
                <div class="col-2 d-flex align-items-center justify-content-center pr-0">
                    <img src="<?= Helpers::printIfExternal(Authentication::User()->display_pic); ?>" alt="" class="form-profile">
                </div>
                <div class="col-10 d-flex align-items-center pl-0">
                    <form action="<?= $_SERVER["PHP_SELF"]; ?>?post_id=<?= $post->id; ?>" class="comment-area pl-4" id="commentForm" method="post">
                        <textarea class="form-control text-area d-flex" name="commentBody" id="comment" rows="1" placeholder="Leave a comment:"></textarea>
                        <input type="submit" name="commentAdd" class="hidden" id="commentAdd">
                    </form>
                </div>
            </div>
        <?php endif; ?>

        <?php foreach ($post->comments() as $announcement) : ?>
        <?php if ($announcement instanceof Comment) : ?>
            <?php $commentOwner = $announcement->user() ?>
            <div class="comment">
            <div class="row">
                <div class="col-3">
                    <div class="image">
                        <img src="<?= Helpers::printIfExternal($commentOwner->display_pic); ?>" alt="" class="comment-pic">
                    </div>
                </div>
                <div class="col-9">
                    <div class="commentinfo">
                        <a href="../../users/view.php?id=<?= $commentOwner->id; ?>" class="comment-user"><?= $commentOwner->name();?></a>
                        <p class="comment-body"><?= $announcement->body; ?></p>
                        <div class="extra">
                            <?php if (Authentication::isLoggedOn()) : ?>
                                <button class="dprim-btn dprim-btn-filled reply-btn" role="button" id="<?= $announcement->id ?>">Reply</button>
                                <div class="popover reply reply-popover" id="reply-<?= $announcement->id ?>">
                                    <form action="<?= $_SERVER["PHP_SELF"] ?>" method="post">
                                        <div class="d-flex flex-column justify-content-center p-3">
                                            <textarea class="msg-box form-control" name="message" placeholder="Enter Reply..."></textarea>
                                            <input type="text" class="hidden" name="comment_id" value="<?= $announcement->id ?>" readonly>
                                            <button type="submit" name="sendReply" class="mt-3 dprim-btn dprim-btn-outline">Send</button>
                                        </div>
                                    </form>
                                </div>
                            <?php endif; ?>
                            <span class="time-info ml-auto"><?= Helpers::getTimeSinceMin($announcement->timestamp); ?></span>
                            <?php if (Authentication::isLoggedOn() && $announcement->isOwner(Authentication::User())) : ?>
                                <form class="ml-3" method="post" action="<?= $_SERVER["PHP_SELF"]; ?>?post_id=<?= $post->id ?>&comment_id=<?= $announcement->id; ?>">
                                    <button type="submit" name="commentDelete" class="btn btn-outline-danger btn-sm">delete</button>
                                </form>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php endif; endforeach; ?>
    </div>
    <div class="col-md-6 text-right">
        <h3>Announcements</h3>
        <?php if(Authentication::isLoggedOn() && $view->owner) : ?>
            <form action="<?= $_SERVER["PHP_SELF"] ?>?post_id=<?= $post->id; ?>" method="POST">
                <div class="announcement-box row p-2 m-0 ml-auto">
                    <div class="col-9 d-flex align-items-center pl-0">
                        <div class="comment-area pl-4">
                            <textarea class="form-control text-area d-flex" name="announcement" id="announce" rows="1" placeholder="Write Announcement..."></textarea>
                        </div>
                    </div>
                    <div class="col-3 d-flex align-items-center justify-content-center pr-0">
                        <img src="<?= Helpers::printIfExternal(Authentication::User()->display_pic); ?>" alt="" class="form-profile">
                    </div>
                </div>
                <input type="submit" name="announcementAdd" value="Announce" class="dprim-btn dprim-btn-filled mr-0 mt-2">
            </form>
        <?php endif; ?>

        <?php foreach ($post->announcements() as $announcement) : ?>
            <?php if ($announcement instanceof Announcement) : ?>
                <div class="comment">
                    <div class="row">
                        <div class="col-3">
                            <div class="image">
                                <img src="<?= Helpers::printIfExternal($post->user()->display_pic) ?>" alt="" class="comment-pic">
                            </div>
                        </div>
                        <div class="col-9">
                            <div class="commentinfo">
                                <p class="comment-body"><?= $announcement->body; ?></p>
                                <div class="extra">
                                    <span class="time-info ml-auto"><?= Helpers::getTimeSinceMin($announcement->timestamp); ?></span>
                                    <?php if (Authentication::isLoggedOn() && $view->owner) : ?>
                                        <form class="ml-3" method="post" action="<?= $_SERVER["PHP_SELF"]; ?>?post_id=<?= $post->id ?>&announcement_id=<?= $announcement->id; ?>">
                                            <button type="submit" name="announcementDelete" class="btn btn-outline-danger btn-sm">delete</button>
                                        </form>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif; endforeach; ?>
    </div>
</div>


<script>
    document.addEventListener("DOMContentLoaded", () => {
        $(".reply-btn").on("click", function() {
            let replies = $(".reply-popover");
            let id = "reply-" + this.id;
            replies.each(function(index) {
                if (this.id !== id)
                    $(this).slideUp(250);
            });
            $("#reply-"+this.id).slideToggle(500);
        });
    });
</script>