
<!-- FOOTER -->
<footer class="d-flex flex-column">
    <?php if ($view->user == true) : ?>
        <div class="chat-button-contain">
            <a class="chat-button" href="#"><span>Chat</span></a>
        </div>
    <?php endif ?>
    <div class="banner">
        <div class="image"></div>
    </div>
    <div class="footer-addon d-flex align-items-center justify-content-around mt-auto">
        <p>Copyright &copy; N.Bamford 2019 &dash; 2020 All Rights Reserved.</p>
        <p>-</p>
        <p class="info"><a href="#">Terms</a><a href="#">Privacy Policy &amp; Cookies</a><a href="#">Security</a></p>
    </div>
</footer>

<!-- BOOTSTRAP JS -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="../js/scripts.js"></script>

</body>
</html>