<!doctype html>
<html lang="en">
<head>
    <!-- Meta -->
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="author" content="Nathan Bamford">

    <!-- Favicon & Title -->
    <link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
    <title><?= $view->title; ?></title>

    <!-- Font & Styles -->
    <link rel="stylesheet" href="../font-awesome/css/all.css">
    <script defer src="../font-awesome/js/all.js"></script>
<!--    <script src="https://kit.fontawesome.com/8aa396f8e9.js"></script>-->

    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="../css/styles.css" type="text/css">
    <link rel="stylesheet" href="../css/sassStyles.css" type="text/css">

    <script src="https://js.pusher.com/5.0/pusher.min.js"></script>

</head>
<body>

<script>
    // Pusher.logToConsole = true;
</script>


<nav class="navbar <?php if(strcmp($view->pageName, "index")) echo "navbar-expand-lg" ?> navbar-light shadow mb-4">
    <div class="container my-auto">
        <a class="navbar-brand mr-5" href="../index.php"><img src="../img/UGAMELOGO1.svg" alt="u-game logo"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle-Navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-between" id="navbarToggler" aria-expanded="false">
            <div class="navbar-nav my-sm-3">
                <a href="../games.php" class="nav-item nav-link <?= $view->pageName != "games" ?: "active-link" ?>">Games</a>
                <a href="../trending.php" class="nav-item nav-link <?= $view->pageName != "trending" ?: "active-link" ?>">Trending</a>
                <a href="../search.php" class="nav-item nav-link <?= $view->pageName != "search" ?: "active-link" ?>">Search</a>
            </div>
            <?php if (Authentication::isLoggedOn()) : ?>
                <!-- USER LOGGED IN -->
                <div class="balance d-flex flex-row align-items-center justify-content-center">
                    <i class="far fa-money-bill-alt mr-2"></i>
                    <p class="m-0">Balance: <span class="text-info"><?= Helpers::displayBalance(Authentication::User()->balance) ?></span></p>
                </div>
                <div class="user d-inline">
                    <div class="text-center">
                        <a href="../users/profile.php?tab=details" class="m-0 username text-body <?php Helpers::echoActive($view->pageName, "profile") ?>" data-toggle="tooltip" data-placement="bottom" title="Profile">
                            <?= Authentication::User()->display_name != "" ?
                                Authentication::User()->display_name : Authentication::User()->first_name;?>
                        </a>
                    </div>
                    <a class="btn toolover <?php if($view->pageName == "create-post") echo "active-link"; ?>" href="../posts/create.php" data-toggle="tooltip" data-placement="bottom" title="Create New Post"><i class="fas fa-edit"></i></a>
                    <div class="notify-drop d-inline-block" data-placement="bottom" title="Notifications">
                        <?php require_once "notifications.phtml" ?>
                    </div>
                    <a class="btn toolover logout" href="../users/logout.php" data-toggle="tooltip" data-placement="bottom" title="Logout"><i class="fas fa-sign-out-alt"></i></a>
                </div>
            <?php else : ?>
                <!-- USER NOT LOGGED IN -->
                <div class="login d-inline">
                    <a href="../users/create.php#signup" class="btn prim-btn my-3 mx-1" style="border-radius: 12px">Sign Up<i class="fas fa-user-plus ml-2"></i></a>
                    <a href="../users/login.php" class="btn btn-outline-secondary my-3 mx-1" style="border-radius: 12px">Login<i class="fas fa-sign-in-alt ml-2"></i></a>
                </div>
            <?php endif ?>
        </div>
    </div>
</nav>

<?php if ($message = FlashMessager::getMessage()) : ?>
<div class="alert alert-<?= $message->colour; ?> alert-dismissable fade show d-flex flex-row align-items-center justify-content-between" role="alert">
    <div class="ml-5">
        <h4><?= $message->body; ?></h4>
        <?php if(isset($message->extra)) foreach ($message->extra as $extra) : ?>
            <p><?= $extra; ?></p>
        <?php endforeach; ?>
    </div>
    <button role="button" class="close ml-auto mr-5" data-dismiss="alert" aria-label="close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<?php endif; ?>

<?php if ($toast = FlashMessager::getToast()) : ?>
    <div class="toast success" style="position: absolute; right: 10em; top: 5em;" data-delay="7500" aria-live="assertive" role="alert">
        <div class="toast-header">
            <span class="text-danger"><?= $toast->icon ?></span>
            <strong class="mr-auto"><?= $toast->title; ?></strong>
            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="toast-body">
            <?= $toast->body ?>
        </div>
    </div>
<?php endif;?>



<script>
    document.addEventListener("DOMContentLoaded", () => {
       $(".toast").toast("show");
    });
</script>
