<?php
    $conversation = new Coversation($mDisplay->user_id_from);

    $userFrom = $conversation->userFrom;
    $messages = $conversation->getMessages();
?>


<div class="message d-flex flex-column">
    <div class="message-header sticky-top text-center">
        <span><?= $userFrom->display_name ?: $userFrom->name() ?></span>
    </div>
    <?php foreach ($messages as $message) : ?>
        <?php if ($message->own) : ?>
            <div class="msg-container self">
                <div class="msg self">
                    <p class="m-body m-0"><?= $message->body ?></p>
                    <span class="text-muted m-date small"><?= Helpers::getTimeSinceMin($message->timestamp);  ?></span>
                </div>
                <img src="<?= Helpers::printIfExternal($userFrom->display_pic) ?>" alt="profile picture" class="user-thumbnail tiny">
            </div>
        <?php else :  ?>
            <div class="msg-container">
                <img src="<?= Helpers::printIfExternal($userFrom->display_pic) ?>" alt="profile picture" class="user-thumbnail">
                <div class="msg">
                    <p class="m-body m-0"><?= $message->body ?></p>
                    <span class="text-muted m-date small"><?= Helpers::getTimeSinceMin($message->timestamp);  ?></span>
                </div>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>