<div class="watch-wrapper sticky-top">
    <div class="watchlist-sidebar">
        <div class="watchlist-sidebar-head-container">
            <h3 class="m-0">Your Messages</h3>
        </div>

        <div class="watchlist-sidebar-body-container msg-sidebar">
            <div id="messages">
                <div class="message-header">
                    <i class="fas fa-caret-left"></i>
                    <h2>Banoulka</h2>
                </div>
                <div class="single-message self">
                    <p>Message Body</p>
                    <small>24m</small>
                </div>
                <div class="single-message">
                    <p>Message Body</p>
                    <small>24m</small>
                </div>
                <div class="single-message self">
                    <p>Message Body</p>
                    <small>24m</small>
                </div>
            </div>
        </div>
    </div>
    <a href="users/profile.php?tab=settings" class="sidebar-edit-link">Edit Your Sidebar</a>
</div>

<script>
    document.addEventListener("DOMContentLoaded", async () => {

        const res = await fetch("../requests/auth/me");
        const data = await res.json();
        const user = data.user;

        const messagesList = $("#messages");

        if (user) {
            await getSlimfo();
        }

        async function getSlimfo() {
            messagesList.slideUp();
            const res = await fetch("../requests/messages/slimfo");
            const json = await res.json();
            const info = json.info;

            messagesList[0].innerHTML = "";

            info.forEach(item => {
                // Destruct
                const { display_name, first_name, last_name, lmessage, latest, Unread, user_id} = item;

                let unread = parseInt(Unread) > 0 ? "unread" : "";
                let displayName = !display_name ? first_name + " " + last_name : display_name;

               let htmlString = `
                   <div class="message ${unread}" id="c-${user_id}">
                        <h2>${displayName}</h2>
                        <p>${lmessage}</p>
                        <small>${latest}</small>
                    </div>
               `;

               messagesList.append(htmlString);

            });

            let messages = document.getElementsByClassName("message");
            messagesList.slideDown();
            for(let message of messages) {
                message.addEventListener("click", displaySingleConversation);
            }
        }

        let loadingMessages = true;

        async function displaySingleConversation(e) {
            messagesList.slideUp();
            let id = this.id.substr(2);

            // Get the single conversation
            const res = await fetch(`../requests/messages/conversation/${id}`);
            const json = await res.json();

            messagesList[0].innerHTML = "";

            // Display the header
            let htmlString = `
                <div class="message-header">
                    <i class="fas fa-caret-left" id="back-btn"></i>
                    <h2>${json.userFrom.first_name}</h2>
                </div>
            `;

            messagesList.append(htmlString);

            let messages = json.messages;

            messages.forEach(item => {
                const { body, timestamp, read, own } = item;
                let self = own ? "self" : "";

                let htmlString = `
                        <div class="single-message ${self}">
                            <p>${body}</p>
                            <small>${timestamp}</small>
                        </div>`;

                messagesList.append(htmlString);
            });

            document.getElementById("back-btn").addEventListener("click", getSlimfo);

            messagesList.slideDown();
        }

    });
</script>