<?php
    $conversation = new Coversation($mDisplay->user_id_from);

    $userFrom = $conversation->userFrom;
    $messages = $conversation->getMessages();
?>


<div class="message d-flex flex-column">
    <div class="message-header sticky-top text-center">
        <a href="view.php?id=<?= $userFrom->id?>"><?= $userFrom->display_name ?: $userFrom->name() ?></a>
    </div>
    <?php foreach ($messages as $message) : ?>
        <?php if ($message->own) : ?>
            <div class="msg-container self">
                <div class="msg self">
                    <p class="m-body m-0"><?= $message->body ?></p>
                    <span class="text-muted m-date small"><?= Helpers::getTimeSinceMin($message->timestamp);  ?></span>
                </div>
                <?php if ($message == end($messages) && $message->read) : ?>
                    <img src="<?= Helpers::printIfExternal($userFrom->display_pic) ?>" alt="profile picture" class="user-thumbnail tiny">
                <?php elseif ($message == end($messages)) : ?>
                    <i class="fas fa-check-circle sent-icon"></i>
                <?php endif; ?>
            </div>
        <?php else :  ?>
            <div class="msg-container">
                <img src="<?= Helpers::printIfExternal($userFrom->display_pic) ?>" alt="profile picture" class="user-thumbnail ml-2">
                <div class="msg">
                    <p class="m-body m-0"><?= $message->body ?></p>
                    <span class="text-muted m-date small"><?= Helpers::getTimeSinceMin($message->timestamp);  ?></span>
                </div>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>