<?php
    require_once $_SERVER["DOCUMENT_ROOT"] . "/Models/Notification.php";
    $userNotifs = Authentication::User()->notifications();

    $countUnread = 0;
    foreach ($userNotifs as $notifs) { if (!$notifs->isRead()) $countUnread++; }
?>

<a tabindex="0" class="btn" data-toggle="popover" role="button"><i class="fas fa-bell"></i>
    <?php if ($countUnread > 0) : ?>
    <span class="badge badge-danger"><?= $countUnread; ?></span>
    <?php endif; ?>
</a>

<div id="notif-col" class="notif-col">
    <div class="popover d-flex flex-column bs-popover-bottom show notif-overlay">
        <div class="arrow align-self-end"></div>
        <div class="popover-header d-flex flex-row align-items-center">
            <h6>Notifications</h6>
            <a href="#" class="ml-auto"><i class="fas fa-cog ml-1"></i></a>
        </div>
        <div class="popover-body">
            <?php if (count($userNotifs) == 0) :  ?>
                <p class="text-muted pl-5">No notifications...</p>
            <?php else : ?>
                <?php foreach ($userNotifs as $notif) : ?>
                    <a href="<?= $notif->link; ?>&notif_id=<?= $notif->id ?>" class="notification-link">
                        <div class="notification d-flex flex-row align-items-center <?= $notif->isRead() ? "" : "notification-unread"; ?>">
                            <img src="<?= $notif->userFrom()->display_pic; ?>" class="notif-profile-pic" alt="">
                            <p><span class="notif-profile-name"><?= $notif->userFrom()->name(); ?></span> <?= $notif->getMessage(); ?></p>
                            <div class="time-icon">
                                <i class="<?= $notif->getIconClass(); ?>"></i>
                                <span class="time-text"><?= $notif->getTimeSince(); ?></span>
                            </div>
                        </div>
                    </a>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
        <!-- NOTIFICATIONS ENDS -->
    </div>
</div>