<a tabindex="0" class="btn" data-toggle="popover" role="button"><i class="fas fa-bell"></i>
    <!-- BADGE FOR NOTIF NUMBER TODO: ADD DYNAMIC NUMBER -->
    <span class="badge badge-danger">4</span>
</a>
<div id="notif-col" class="notif-col">
    <div class="popover d-flex flex-column bs-popover-bottom show notif-overlay">
        <div class="arrow align-self-end"></div>
        <div class="popover-header d-flex flex-row align-items-center">
            <h6>Notifications</h6>
            <a href="#" class="ml-auto"><i class="fas fa-cog ml-1"></i></a>
        </div>
        <div class="popover-body">
            <!-- Notifcation x3 -->
            <!--                                    <p class="text-muted">No new notifications...</p>-->
            <!-- TODO: ADD TIME?? -->
            <div class="notification d-flex flex-row align-items-center notification-unread">
                <img src="/uploads/profile_pictures/profilepic1.png" class="notif-profile-pic" alt="">
                <p><span class="notif-profile-name">Mark Hamill</span> liked your post.</p>
                <i class="fas fa-thumbs-up"></i>
            </div>

            <div class="notification d-flex flex-row align-items-center notification-unread">
                <img src="/uploads/profile_pictures/profilepic3.png" class="notif-profile-pic" alt="">
                <p><span class="notif-profile-name">John Albertross</span> added your post to their watchlist.</p>
                <i class="fas fa-eye"></i>
            </div>

            <div class="notification d-flex flex-row align-items-center notification-unread">
                <img src="/uploads/profile_pictures/profilepic4.png" class="notif-profile-pic" alt="">
                <p><span class="notif-profile-name">Sophie Whineston</span> has just uploaded a new post.</p>
                <i class="fas fa-rss"></i>
            </div>

            <div class="notification d-flex flex-row align-items-center">
                <img src="/uploads/profile_pictures/profilepic2.png" class="notif-profile-pic" alt="">
                <p><span class="notif-profile-name">Max Eves</span> liked your post.</p>
                <i class="fas fa-thumbs-up"></i>
            </div>

            <div class="notification d-flex flex-row align-items-center">
                <img src="/uploads/profile_pictures/profilepic2.png" class="notif-profile-pic" alt="">
                <p><span class="notif-profile-name">Max Eves</span> commented on your post.</p>
                <i class="fas fa-comment-dots"></i>
            </div>

            <div class="notification d-flex flex-row align-items-center">
                <img src="/uploads/profile_pictures/profilepic1.png" class="notif-profile-pic" alt="">
                <p><span class="notif-profile-name">Mark Hamill</span> started following you.</p>
                <i class="fas fa-user-friends"></i>
            </div>

            <div class="notification d-flex flex-row align-items-center">
                <img src="/uploads/profile_pictures/profilepic3.png" class="notif-profile-pic" alt="">
                <p><span class="notif-profile-name">John Albertross</span> liked your post.</p>
                <i class="fas fa-thumbs-up"></i>
            </div>

            <div class="notification d-flex flex-row align-items-center">
                <img src="/uploads/profile_pictures/profilepic4.png" class="notif-profile-pic" alt="">
                <p><span class="notif-profile-name">Sophie Whineston</span> commented on your post.</p>
                <i class="fas fa-comment-dots"></i>
            </div>

            <div class="notification d-flex flex-row align-items-center notification-unread">
                <img src="/uploads/profile_pictures/profilepic2.png" class="notif-profile-pic" alt="">
                <p><span class="notif-profile-name">Max Eves</span> commented on your post.</p>
                <i class="fas fa-comment-dots"></i>
            </div>

            <div class="notification d-flex flex-row align-items-center">
                <img src="/uploads/profile_pictures/profilepic1.png" class="notif-profile-pic" alt="">
                <p><span class="notif-profile-name">Mark Hamill</span> added your post to their watchlist.</p>
                <i class="fas fa-eye"></i>
            </div>

            <div class="notification d-flex flex-row align-items-center">
                <img src="/uploads/profile_pictures/profilepic3.png" class="notif-profile-pic" alt="">
                <p><span class="notif-profile-name">John Albertross</span> has just uploaded a new post.</p>
                <i class="fas fa-rss"></i>
            </div>

        </div>
        <!-- NOTIFICATIONS ENDS -->
    </div>
</div>