<div class="watch-wrapper sticky-top">
<div class="watchlist-sidebar">
    <div class="watchlist-sidebar-head-container">
        <h3 class="m-0">Your Watchlist</h3>
    </div>
    <div class="watchlist-sidebar-body-container">
        <?php foreach ($view->userWatchlist as $post) : ?>
            <?php if ($post instanceof Post) : ?>
                <a href="<?= "http://" . $_SERVER["HTTP_HOST"]; ?>/posts/view.php?post_id=<?= $post->id; ?>&" class="watchlist-link">
                    <div class="watchlist-sidebar-item">
                        <div class="watchlist-sidebar-item-body">
                            <h4 class="watchlist-title"><?= substr($post->title, 0, 28); ?></h4>
                            <div class="watchlist-sidebar-item-detail-container">
                                <p class="watchlist-item-author"><?= $post->user()->name(); ?></p>
                                <span class="icon-count"><i class="far fa-thumbs-up"></i><?= $post->likesCount(); ?></span>
                                <span class="icon-count"><i class="fas fa-eye"></i><?= $post->watchCount(); ?></span>
                                <span class="icon-count"><i class="far fa-comment-dots"></i><?= $post->commentCount(); ?></span>
                            </div>
                        </div>
                        <div class="watchlist-sidebar-item-colour watchlist-item-<?= $post->type_stage; ?>"></div>
                    </div>
                </a>
            <?php endif; endforeach; ?>
    </div>
</div>
<a href="#" class="sidebar-edit-link">Edit Your Sidebar</a>
</div>