<div class="profile-header">
    <h1>Your Profile:</h1>
</div>
<div class="profile-menu">
    <a href="<?= $profilePage; ?>details" class="menu-item <?php Helpers::echoActive($view->tab, "details"); ?>">Details</a>
    <a href="<?= $profilePage; ?>messages" class="menu-item <?php Helpers::echoActive($view->tab, "messages");?>">Messages</a>
    <a href="<?= $profilePage; ?>posts" class="menu-item <?php Helpers::echoActive($view->tab, "posts");?>">Posts</a>
    <a href="#" class="menu-item">Watchlist</a>
    <a href="#" class="menu-item">Settings</a>
</div>