<?php require("partials/header.phtml") ?>
<div class="container section">
    <div class="row">
        <div class="col-lg-8">
            <h1 class="title">Trending Now<i class="fas fa-caret-down ml-5"></i></h1>
            <label class="minified-label">
                <input type="checkbox" class="minified-input">
                <span class="minified-checkbox"></span><span>Minified View?</span>
            </label>
            <div class="posts">
                    <a href="#" class="post-reg alpha">
                        <div class="row">
                            <div class="col-5">
                                <img src="/img/artwork.png" alt="" class="game-cover">
                            </div>
                            <div class="col">
                                <h3 class="post-title">Gears of War 4</h3>
                                <p class="author">Johnny Davidson</p>
                                <p class="content"></p>
                            </div>
                            <div class="post-colour alpha"><span>Alpha</span></div>
                        </div>
                    </a>
            </div>
        </div>
        <div class="col-lg-4 d-none d-lg-block">
            <!-- TODO: Add dynamic sidebar-->
            <?php require("partials/watchlist-sidebar.phtml") ?>
        </div>
    </div>
</div> <!-- Container end -->

<?php require("partials/footer.phtml") ?>