<?php require("partials/header.phtml") ?>
<div class="container">
    <h1 class="text-danger">Welcome to page 1</h1>
    <h1>Welcome to page 1</h1>
    <h1>Welcome to page 1</h1>
    <h1>Welcome to page 1</h1>
    <h1>Welcome to page 1</h1>
    <h1>Welcome to page 1</h1>
    <h1>Welcome to page 1</h1>
    <h1>Welcome to page 1</h1>
    <h1>Welcome to page 1</h1>
    <h1>Welcome to page 1</h1>
    <h1>Welcome to page 1</h1>
    <h1>Welcome to page 1</h1>
</div> <!-- Container end -->

<?php require("partials/footer.phtml") ?>