<?php require("partials/header.phtml") ?>
<div class="container section px-0">
    <div class="row">
        <div class="col-12 px-lg-0 px-xl-2 col-lg-8">
            <h1 class="title">Trending Now<i class="fas fa-caret-down ml-5"></i></h1>
            <label class="minified-label">
                <input type="checkbox" class="minified-input">
                <span class="minified-checkbox"></span><span>Minified View?</span>
            </label>
            <div class="posts">
                <a href="/posts/read.php" class="post-reg">
                    <div class="rows d-flex">
                        <div class="row">
                            <div class="col-5">
                                <img src="/img/artwork.png" alt="" class="game-cover">
                            </div>
                            <div class="col">
                                <h3 class="post-title">Gears of War 4</h3>
                                <p class="author">Johnny Davidson</p>
                                <p class="content">Gears of war is about burley man sitting behind cover and shooting at the mean baddies. Aliens come to invade earth like they do and finally a big burley man with armour as big as kitchenware is sent into the depths of hell to purge the alien scum away from our beloved.</p>
                                <div class="tags">
                                    <p class="tag">Space Combat</p>
                                    <p class="tag">Adventure</p>
                                    <p class="tag">Space</p>
                                    <p class="tag">Sci-fi</p>
                                </div>
                            </div>
                            <div class="row extras">
                                <span class="likes"><i class="far fa-thumbs-up"></i>45</span>
                                <span class="watches"><i class="fas fa-eye"></i>23</span>
                                <span class="comments"><i class="far fa-comment-dots"></i>52</span>
                            </div>
                        </div>
                        <div class="post-colour"><span class="released"></span></div>
                    </div>
                </a>
                <a href="#" class="post-reg">
                    <div class="rows d-flex">
                        <div class="row">
                            <div class="col-5">
                                <img src="/img/artwork.png" alt="" class="game-cover">
                            </div>
                            <div class="col">
                                <h3 class="post-title">Gears of War 4</h3>
                                <p class="author">Johnny Davidson</p>
                                <p class="content">Gears of war is about burley man sitting behind cover and shooting at the mean baddies. Aliens come to invade earth like they do and finally a big burley man with armour as big as kitchenware is sent into the depths of hell to purge the alien scum away from our beloved.</p>
                                <div class="tags">
                                    <p class="tag">Space Combat</p>
                                    <p class="tag">Adventure</p>
                                    <p class="tag">Space</p>
                                    <p class="tag">Sci-fi</p>
                                </div>
                            </div>
                            <div class="row extras">
                                <span class="likes"><i class="far fa-thumbs-up"></i>45</span>
                                <span class="watches"><i class="fas fa-eye"></i>23</span>
                                <span class="comments"><i class="far fa-comment-dots"></i>52</span>
                            </div>
                        </div>
                        <div class="post-colour"><span class="released"></span></div>
                    </div>
                </a>
                <a href="#" class="post-reg">
                    <div class="rows d-flex">
                        <div class="row">
                            <div class="col-5">
                                <img src="/img/artwork.png" alt="" class="game-cover">
                            </div>
                            <div class="col">
                                <h3 class="post-title">Gears of War 4</h3>
                                <p class="author">Johnny Davidson</p>
                                <p class="content">Gears of war is about burley man sitting behind cover and shooting at the mean baddies. Aliens come to invade earth like they do and finally a big burley man with armour as big as kitchenware is sent into the depths of hell to purge the alien scum away from our beloved.</p>
                                <div class="tags">
                                    <p class="tag">Space Combat</p>
                                    <p class="tag">Adventure</p>
                                    <p class="tag">Space</p>
                                    <p class="tag">Sci-fi</p>
                                </div>
                            </div>
                            <div class="row extras">
                                <span class="likes"><i class="far fa-thumbs-up"></i>45</span>
                                <span class="watches"><i class="fas fa-eye"></i>23</span>
                                <span class="comments"><i class="far fa-comment-dots"></i>52</span>
                            </div>
                        </div>
                        <div class="post-colour"><span class="released"></span></div>
                    </div>
                </a>
                <a href="#" class="post-reg">
                    <div class="rows d-flex">
                        <div class="row">
                            <div class="col-5">
                                <img src="/img/artwork.png" alt="" class="game-cover">
                            </div>
                            <div class="col">
                                <h3 class="post-title">Gears of War 4</h3>
                                <p class="author">Johnny Davidson</p>
                                <p class="content">Gears of war is about burley man sitting behind cover and shooting at the mean baddies. Aliens come to invade earth like they do and finally a big burley man with armour as big as kitchenware is sent into the depths of hell to purge the alien scum away from our beloved.</p>
                                <div class="tags">
                                    <p class="tag">Space Combat</p>
                                    <p class="tag">Adventure</p>
                                    <p class="tag">Space</p>
                                    <p class="tag">Sci-fi</p>
                                </div>
                            </div>
                            <div class="row extras">
                                <span class="likes"><i class="far fa-thumbs-up"></i>45</span>
                                <span class="watches"><i class="fas fa-eye"></i>23</span>
                                <span class="comments"><i class="far fa-comment-dots"></i>52</span>
                            </div>
                        </div>
                        <div class="post-colour"><span class="released"></span></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="d-none px-lg-0 px-xl-2 col-lg-4 d-lg-block">
            <!-- TODO: Add dynamic sidebar-->
            <?php require("partials/watchlist-sidebar.phtml") ?>
        </div>
    </div>
</div> <!-- Container end -->

<?php require("partials/footer.phtml") ?>