<?php require("partials/header.phtml"); ?>

<div class="container section px-0">
    <form action="<?= $_SERVER["PHP_SELF"]; ?>" method="GET" class="search-form row" id="search">
        <aside class="collapse-sidebar">
            <div id="dismiss-sidebar"><i class="far fa-times-circle"></i></div>
            <div class="collapse-sidebar-header">
                <h2>Refine Search</h2>
            </div>
            <div id="filters-sidebar-section" class="my-3"></div>
            <div id="sortby-sidebar-section" class="my-3"></div>
            <div id="tags-sidebar-section" class="my-3"></div>
        </aside>

        <div class="col-12 px-lg-0 px-xl-2 col-lg-12 col-xl-9">
            <div class="row">
                <div class="col-md-12 col-lg-8">
                    <h1 class="title px-2">Search Posts <span id="sidebar-open" class="sidebar-icon"><i class="fas fa-bars"></i></span></h1>
                    <!-- Hidden minified form -->
                        <label class="minified-label">
                            <input id="mini-checkbox" type="checkbox" class="minified-input">
                            <span class="minified-checkbox"></span><span>Minified View?</span>
                        </label>
                    <!-- end hidden form -->
                    <div class="row my-3 align-items-center">
                        <div class="col-4 px-3">
                            <select class="form-control search-select" name="search-type" id="search-type">
                                <option value="title">Title</option>
                                <option value="author">Author</option>
                            </select>
                        </div>
                        <div class="col-8 px-4">
                            <input type="text" class="form-control" id="search-box" name="search" placeholder="Search text" autocomplete="off" value="<?php if (isset($view->searches)) echo $view->searches["search"]; ?>">
                            <div class="suggest-box" id="suggest-box">
                                <div class="arrow"></div>
                                <div class="header">
                                    <h3 class="title">Suggestions:</h3>
                                    <i class="fas fa-times" id="close"></i>
                                </div>
                                <div id="suggestions">
                                    <div id="suggestion-loader">
                                        <span></span>
                                        <span></span>
                                        <span></span>
                                    </div>
                                    <a class="suggestion">
                                        <img src="/uploads/profile_pictures/nodp.png" alt="" class="picture">
                                        <div class="name">
                                            <span>Nathan Bamford</span>
                                            <span>Banoulka</span>
                                        </div>
                                        <span class="likes">
                                            30
                                            <i class="fas fa-user-friends"></i>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col px-4">
                            <button type="submit" name="submit" class="dprim-btn dprim-btn-filled m-0">Search<i class="fas fa-search pl-2"></i></button>
                            <?php if (isset($view->resultsCount)) : ?>
                            <span class="text-info" style="margin-left: 15em"><?= $view->resultsCount?> results...</span>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <div class="col-2 search-col collapsable" id="sort-row-main">
                    <div id="sort-content">
                    <h3 class="search-titles">Sort By</h3>
                    <div class="column">
                        <div class="sort-by-option">
                            <label>Relevance<input type="radio" value="relevance" name="sort-by" class="sort-by-radio" <?php if (isset($view->searches) && $view->searches["sort-by"] == "relevance") echo "checked" ?>></label>
                        </div>
                        <div class="sort-by-option">
                            <label>Likes<input type="radio" value="likes" name="sort-by" class="sort-by-radio" <?php if (isset($view->searches) && $view->searches["sort-by"] == "likes") echo "checked" ?>></label>
                        </div>
                        <div class="sort-by-option">
                            <label>Watches<input type="radio" value="watches" name="sort-by" class="sort-by-radio" <?php if (isset($view->searches) && $view->searches["sort-by"] == "watches") echo "checked" ?>></label>
                        </div>
                        <div class="sort-by-option">
                            <label>Comments<input type="radio" value="comments" name="sort-by" class="sort-by-radio" <?php if (isset($view->searches) && $view->searches["sort-by"] == "comments") echo "checked" ?>></label>
                        </div>
                        <div class="sort-by-option">
                            <label>Newest<input type="radio" value="newest" name="sort-by" class="sort-by-radio" <?php if (isset($view->searches) && $view->searches["sort-by"] == "newest") echo "checked" ?>></label>
                        </div>
                    </div>
                    </div>
                </div>
                <div class="col-2 search-col collapsable" id="filter-row-main">
                    <div id="filter-content">
                    <h3 class="search-titles">Filters</h3>
                    <div class="column">
                        <div class="filter-option">
                            <label id="followed-label">Followed<input type="checkbox" class="filter-by-checkbox" value="followed" <?php if (isset($view->searches["filters"]) && in_array("followed", $view->searches["filters"])) echo "checked" ?>></label>
                        </div>
                        <div class="filter-option">
                            <label id="alpha-label">Alpha<input type="checkbox" class="filter-by-checkbox" name="filters[]" value="alpha" <?php if (isset($view->searches["filters"]) && in_array("alpha", $view->searches["filters"])) echo "checked" ?>></label>
                        </div>
                        <div class="filter-option">
                            <label id="beta-label">Beta<input type="checkbox" class="filter-by-checkbox" name="filters[]" value="beta" <?php if (isset($view->searches["filters"]) && in_array("beta", $view->searches["filters"])) echo "checked" ?>></label>
                        </div>
                        <div class="filter-option">
                            <label id="concept-label">Concept<input type="checkbox" class="filter-by-checkbox" name="filters[]" value="concept" <?php if (isset($view->searches["filters"]) && in_array("concept", $view->searches["filters"])) echo "checked" ?>></label>
                        </div>
                        <div class="filter-option">
                            <label id="released-label">Released<input type="checkbox" class="filter-by-checkbox" name="filters[]" value="released" <?php if (isset($view->searches["filters"]) && in_array("released", $view->searches["filters"])) echo "checked" ?>></label>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="posts">
                        <?php if (isset($view->posts)) : foreach ($view->posts as $post) : ?>
                            <?php if ($post instanceof Post) : ?>
                                <a href="../posts/view.php?post_id=<?= $post->id ?>" class="post-reg">
                                    <div class="rows d-flex">
                                        <div class="row">
                                            <div class="col-5">
                                                <img src="<?= Authentication::isLoggedOn() ? $post->cover_image : "../../uploads/post_covers/cover-hidden.jpg" ?>" alt="" class="game-cover">
                                            </div>
                                            <div class="col-7 min">
                                                <h3 class="post-title"><?= substr($post->title, 0, 33); ?></h3>
                                                <p class="author"><?= $post->user()->name(); ?></p>
                                                <p class="content"><?= $post->description; ?></p>
                                                <div class="tags">
                                                    <?php foreach ($post->tags() as $tag) : ?>
                                                        <p class="tag"><?= $tag->title; ?></p>
                                                    <?php endforeach; ?>
                                                </div>
                                            </div>
                                            <div class="row extras">
                                                <span class="likes"><i class="far fa-thumbs-up"></i><?= $post->likesCount(); ?></span>
                                                <span class="watches"><i class="fas fa-eye"></i><?= $post->watchCount(); ?></span>
                                                <span class="comments"><i class="far fa-comment-dots"></i><?= $post->commentCount(); ?></span>
                                                <span class="ml-3"><?= $post->getTimeSince(); ?></span>
                                            </div>
                                        </div>
                                        <div class="post-colour"><span class="<?= $post->type_stage; ?>"></span></div>
                                    </div>
                                </a>
                            <?php endif; ?>
                        <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                    <!-- Require the Pagination -->
                    <?php require_once "partials/pagination.phtml"?>
                </div>
            </div>
        </div>
        <div class="d-none px-xl-0 col-lg-2 d-lg-block ml-5 collapsable-tags">
            <div class="row" id="tag-row-main">
            <div class="col search-col px-0" id="tag-content">
                <h3 class="search-titles">Tags</h3>
                <div class="check-selections" id="check-buttons-row">
                    <div id="check-buttons-content">
                        <button type="button" class="tag-check-btn" id="check-all-tags">Check All</button>
                        <button type="button" class="tag-check-btn" id="uncheck-all-tags">Uncheck All</button>
                    </div>
                </div>
                <div class="tag-column">
                <?php foreach($view->tags as $tag) : ?>
                    <div class="custom-control custom-checkbox">
                        <input id="<?= $tag->title; ?>-tag" type="checkbox" placeholder="tags[]" class="custom-control-input" value="<?= strtolower($tag->title); ?>" checked>
                        <label class="custom-control-label" for="<?= $tag->title; ?>-tag"><?= $tag->title; ?></label>
                    </div>
                <?php endforeach; ?>
            </div>
            </div>
        </div>
        </div>
    </form>
</div>

<div class="overlay"></div>

<form id="minified-form" class="hidden" action="formtest.php" method="post">
    <input type="checkbox" class="hidden" id="hidden-checkbox" name="minified">
</form>

<script>
    document.addEventListener("DOMContentLoaded", () => {

        let searchType = document.getElementById("search-type");
        let searchBox = document.getElementById("search-box");
        let suggestBox = document.getElementById("suggest-box");

        let suggestionContainer = document.getElementById("suggestions");
        
        let timeout = null;

        searchType.addEventListener("change", function() {
            let value = this.value;
            if (value === "author") {
                searchBox.addEventListener("keyup", suggestSearchesEventHandler);
            } else {
                searchBox.removeEventListener("keyup", suggestSearchesEventHandler);
            }
        });

        document.getElementById("close").addEventListener("click", () => suggestBox.classList.remove("show"));

        function showLoader(bool) {
            console.log("showing loader");
            if (bool) {
                suggestionContainer.innerHTML = `<div id="suggestion-loader">
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                        </div>`;
            } else {
                suggestionContainer.innerHTML = ``;
            }
        }

        async function suggestSearchesEventHandler(e) {

            let suggestionString = this.value;

            // If the box is empty, don't suggest
            if (suggestionString === "") {
                suggestBox.classList.remove("show");
                clearTimeout(timeout);
                return;
            }
            // Clear the old timeout
            if (timeout) {
                clearTimeout(timeout);
            }

            // Set a new timeout
            timeout = setTimeout(() => fetchSuggestions(suggestionString), 2000);
        }

        async function fetchSuggestions(suggestionString) {
            suggestBox.classList.add("show");

            showLoader(true);
            const res = await fetch(`../requests/users/suggest/${suggestionString}`);
            const data = await res.json();
            const { suggestedUsers } = data;

            let html = ``;

            suggestedUsers.forEach(user => {
                const { id, display_pic, name, display_name, followerCount} = user;

                const displayName = display_name ? display_name : "No display name";
                html += `<a class="suggestion" href="../users/view.php?id=${id}">
                            <img src="${display_pic}" alt="" class="picture">
                            <div class="name">
                                <span>${name}</span>
                                <span>${displayName}</span>
                            </div>
                            <span class="likes">
                                ${followerCount}
                                <i class="fas fa-user-friends"></i>
                            </span>
                        </a>`;
            });

            showLoader(false);
            suggestionContainer.innerHTML = html;
        }
    });
</script>

<?php require("partials/footer.phtml"); ?>
