<?php require_once "partials/header.phtml" ?>
<div class="container section px-0">
    <div class="row">
        <div class="col-12 px-lg-0 px-xl-2 col-lg-8">
            <h1 class="title">Trending Posts<i class="fas fa-caret-down ml-5"></i></h1>
            <label class="minified-label">
                <input type="checkbox" class="minified-input">
                <span class="minified-checkbox"></span><span>Minified View?</span>
            </label>
            <div class="posts">
            </div>
            <div class="d-flex justify-content-center align-items-center">
                <div id="loader" class="load-bar">
                    <div class="inner"></div>
                    <div class="inner ghost"></div>
                </div>
            </div>
        </div>
        <div class="d-none px-lg-0 px-xl-2 col-lg-4 d-lg-block">
            <?php
            if (isset($_COOKIE["sidebar"]) && $_COOKIE["sidebar"] == "messages") {
                require("partials/messages-sidebar.phtml");
            } else {
                require("partials/watchlist-sidebar.phtml");
            }
            ?>
        </div>
    </div>
</div> <!-- Container end -->

<script>
    document.addEventListener("DOMContentLoaded", () => {

            const dataDisplayer = new DataDisplayer();

            const loader = $("#loader");
            const postsContainer = document.getElementsByClassName("posts")[0];

            dataDisplayer.setParent(postsContainer);

            let loading = true;

            const user = Authentication.getUser();
            let offset = 0;

            // Get the first set of trending posts
            getTrendingPost();

            function getTrendingPost() {
                toggleLoader(true);

                // Send a fetch request to the server and await the data response
                fetch(`../requests/Posts/trending/${offset}`).then(res => {
                    return res.json();
                }).then(data => {
                    let { posts } = data;
                    // Increment the offset so the next request will get it
                    offset++;

                    // For each post that came in posts
                    for (let post of posts) {
                        // Destruct the post
                        const { cover_image, tags } = post;

                        post.tags = "";

                        for (let tag of tags) {
                            post.tags += tag.title + ", ";
                            // `    <p class="tag">${tag.title}</p>`;
                        }

                        // Work out some default profile pictures and whether it should
                        // display the displayname or the first and last name
                        post.displayName = post.user.display_name || post.user.first_name + " " + post.user.last_name;
                        post.displayPicture = user ? cover_image : "../../uploads/post_covers/cover-hidden.jpg";

                    }
                    dataDisplayer.setData(posts);

                    // Generate a new htmlstring with template tags
                    // and javascript properties
                    let htmlString = `
                        <a href="../posts/view.php?post_id=%id%" class="post-reg">
                            <div class="rows d-flex">
                                <div class="row">
                                    <div class="col-5">
                                        <img src="%displayPicture%" alt="" class="game-cover">
                                    </div>
                                    <div class="col-7 min">
                                        <h3 class="post-title">%title%</h3>
                                        <p class="author">%displayName%</p>
                                        <p class="content">%description%</p>
                                        <div class="tags">
                                            <p class="tag">%tags%</p>
                                        </div>
                                    </div>
                                    <div class="row extras">
                                        <span class="likes"><i class="far fa-thumbs-up"></i>%likeCount%</span>
                                        <span class="watches"><i class="fas fa-eye"></i>%watchCount%</span>
                                        <span class="comments"><i class="far fa-comment-dots"></i>%commentCount%</span>
                                        <span class="ml-3">%time%</span>
                                    </div>
                                </div>
                                <div class="post-colour"><span class="%type_stage%"></span></div>
                            </div>
                        </a>
                    `;

                    // Pass the template into the data displayer
                    dataDisplayer.setTemplate(htmlString);
                    dataDisplayer.display();

                    toggleLoader(false);
                });

            }

            function toggleLoader(bool) {
                if (bool) {
                    loading = true;
                    loader.fadeIn();
                }
                else {
                    loading = false;
                    loader.fadeOut();
                }
            }

            document.addEventListener("scroll", handleScroll);

            function handleScroll() {
                if (!loading) {
                    const { scrollTop, scrollHeight, clientHeight } = document.documentElement;
                    if (scrollTop + clientHeight >= scrollHeight - 500) {
                        // Start loading more posts
                        getTrendingPost();
                    }
                }
            }
    }, false)
</script>

<?php require_once "partials/footer.phtml" ?>