<?php require(__DIR__ . "/../partials/header.phtml"); ?>
<?php $user = Authentication::User();
    $profilePage = "../../users/profile.php?tab=";
?>
<div class="container section">
    <div class="row">
        <div class="col-md-4">
            <?php include_once "profile-tabs/profile-menu.phtml"?>
        </div>
        <div class="col-md-8">
            <div class="menu-display">
                <div class="row">
                    <div class="col-12">
                        <form action="<?php echo $_SERVER["PHP_SELF"]; ?>" method="POST" enctype="multipart/form-data">
                            <div class="d-flex flex-row align-items-center justify-space-between">
                                <input type="text" name="first_name" class="form-control edit-prof mr-3" value="<?php echo $user->first_name ?>" placeholder="<?php echo $user->first_name; ?>">
                                <input type="text" name="last_name" class="form-control edit-prof" value="<?php echo $user->last_name ?>" placeholder="<?php echo $user->last_name; ?>">
                            </div>
                            <p class="aka">aka</p>
                            <input type="text" name="display_name" class="form-control edit-prof" style="font-size: 1.4rem" value="<?php echo $user->display_name != "" ? $user->display_name : "" ?>" placeholder="<?php echo $user->display_name != "" ? $user->display_name : "No display name set" ?>">

                            <label for="email" class="user-label">Email:</label>
                            <input type="email" id="email" name="email" class="form-control edit-prof" style="font-size: 1rem;" value="<?php echo $user->email ?>" placeholder="<?php echo $user->email ?>">
                            <p class="text-warning small mt-1">Changing your email will force a logout</p>

                            <h6 class="user-label">Password:</h6>
                            <p>*********</p>

                            <label for="bio" class="user-label mt-0">Bio:</label>
                            <textarea id="bio" name="bio" class="form-control edit-prof" style="font-size: 1rem;" placeholder="<?php echo $user->bio != "" ? "" : "No bio set" ?>"><?php echo $user->bio != "" ? $user->bio : ""?></textarea>

                            <img src="<?php echo $user->display_pic; ?>" class="profile-pic edit" alt="Profile Picture">
                            <div class="custom-file">
                                <input type="file" name="display_pic" class="custom-file-input" id="custom-file" accept="image/*">
                                <label for="custom-file" class="custom-file-label">Choose file</label>
                            </div>

                            <div class="d-flex flex-row align-items-center">
                                <input type="submit" name="submit" class="btn dprim-btn-filled mt-4 mr-2" value="Save">
                                <a href="profile.php" class="btn btn-outline-dark mt-4 mx-2">Cancel</a>
                                <button type="button" id="modalDelete" class="btn btn-danger mt-4 ml-auto" >Delete Profile <i class="fas ml-1 fa-exclamation-triangle"></i></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(".custom-file-input").on("change", function() {
        var fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
    });
</script>

<div class="modal fade" tabindex="-1" role="dialog" id="deleteProfileModal" style="border: 15px solid rgba(255,39,35,0.7);">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Deleting Profile - <span class="text-info"><?= $user->name(); ?></span></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="m-0">Are you sure you want to delete your profile?</p>
                <p class="m-0">All data associated will be removed.</p>
                <p class="text-danger small mt-2">&gt; This action cannot be reversed.</p>
            </div>
            <div class="modal-footer">
                <form action="delete.php" method="post" id="deleteForm">
                    <input type="hidden" name="auth-token" readonly value="<?= password_hash($user->id, PASSWORD_DEFAULT) ?>">
                </form>
                <button type="button" class="btn btn-danger mr-auto" onclick="document.getElementById('deleteForm').submit()">Yes I am sure</button>
                <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<?php require(__DIR__ . "/../partials/footer.phtml") ?>

<script>
    document.getElementById("modalDelete").addEventListener("click", (e) => {
       $("#deleteProfileModal").modal("show");
    });
</script>