<?php
    require(__DIR__ . "/../partials/header.phtml");
    $user = Authentication::User();
    $profilePage = "../../users/profile.php?tab=";
?>
<div class="container section">
    <div class="row">
        <div class="col-md-4">
            <div class="profile-header">
                <h1>Your Profile:</h1>
            </div>
            <div class="profile-menu">
                <a href="<?= $profilePage; ?>details" class="menu-item <?php Helpers::echoActive($view->tab, "details"); ?>">Details</a>
                <a href="<?= $profilePage; ?>messages" class="menu-item <?php Helpers::echoActive($view->tab, "messages");?>">Messages</a>
                <a href="<?= $profilePage; ?>posts" class="menu-item <?php Helpers::echoActive($view->tab, "posts");?>">Posts</a>
                <a href="#" class="menu-item">Watchlist</a>
                <a href="#" class="menu-item">Settings</a>
            </div>
        </div>
        <div class="col-md-8">
            <div class="menu-display">
                <div class="row">
                    <?php switch ($view->tab) :
                        case "details" : include_once "profile-tabs/details.phtml"; break;
                        case "messages" : include_once "profile-tabs/messages.phtml"; break;
                        case "posts" : include_once "profile-tabs/posts.phtml"; break;
                        default: include_once "profile-tabs/details.phtml";
                    endswitch; ?>
                </div>
            </div>
        </div>
    </div>
</div>

<?php require(__DIR__ . "/../partials/footer.phtml") ?>
