<?php
    require(__DIR__ . "/../partials/header.phtml");
    $user = Authentication::User();
    $profilePage = "../../users/profile.php?tab=";
?>
<div class="container section">
    <div class="row">
        <div class="col-md-4">
            <?php include_once "profile-tabs/profile-menu.phtml"?>
        </div>
        <div class="col-md-8">
            <div class="menu-display">
                <div class="row">
                    <?php switch ($view->tab) :
                        case "details" : include_once "profile-tabs/details.phtml"; break;
                        case "messages" : include_once "profile-tabs/messages.phtml"; break;
                        case "posts" : include_once "profile-tabs/posts.phtml"; break;
                        case "watchlist" : include_once "profile-tabs/watchlist.phtml"; break;
                        case "settings" : include_once "profile-tabs/settings.phtml"; break;
                        default: include_once "profile-tabs/details.phtml";
                    endswitch; ?>
                </div>
            </div>
        </div>
    </div>
</div>

<?php require(__DIR__ . "/../partials/footer.phtml") ?>
