<?php require(__DIR__ . "/../partials/header.phtml"); ?>
<?php $user = $view->user ?>

<div class="container section">
    <?php if($user && $user instanceof User) : ?>
    <div class="row">
        <div class="col-8">
            <h3 class="title"><?= $user->name(); ?></h3>
            <div class="row mt-3">
                <div class="col-4">
                    <img class="profile-pic mt-0" src="<?= $user->display_pic ?>" alt="Profile Picture">
                    <?php if (Authentication::isLoggedOn()) : ?>
                    <form action="<?= $_SERVER["PHP_SELF"]; ?>?id=<?= $user->id; ?>" method="post" class="follow-message">
                        <?php if (Authentication::User()->id == $user->id) : ?>
                        <?php elseif (Authentication::User()->isFollower($user)) : ?>
                            <button type="submit" name="userUnfollow" class="btn btn-danger">Unfollow</button>
                        <?php else : ?>
                            <button type="submit" name="userFollow" class="btn dprim-btn-filled">Follow</button>
                        <?php endif; ?>
                        <?php if (Authentication::User()->id != $user->id) : ?>
                            <a href="#" class="d-block mx-4 mt-3 btn dprim-btn-outline">Message</a>
                        <?php endif; ?>
                    </form>
                    <?php else : ?>
                        <button class="btn disabled">Sign in to follow</button>
                        <button class="btn disabled">Sign in to message</button>
                    <?php endif; ?>
                </div>
                <div class="col-8">
                    <p class="aka">aka</p>
                    <h4 class="mb-4"><?= $user->display_name != "" ? $user->display_name : "No display name set"?></h4>

                    <h6 class="user-label mt-2">Email:</h6>
                    <p><?= $user->email; ?></p>

                    <h6 class="user-label mt-3">Bio:</h6>
                    <p><?= $user->bio != "" ? $user->bio : "No bio set"; ?></p>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="followers">
                <?php $followers = $user->followers(); ?>
                <div class="header">
                    <h4>Followers &dash; <?= count($followers); ?></h4>
                </div>
                <div class="body">
                    <?php foreach ($followers as $follower) : ?>
                    <a href="view.php?id=<?= $follower->id; ?>">
                        <div class="follower">
                            <h5 class="name"><?= $follower->name(); ?></h5>
                            <img class="pic" src="<?= $follower->display_pic; ?>" alt="">
                        </div>
                    </a>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
    <?php else : ?>
        <h1 class="display-4 text-danger text-center">User not found</h1>
        <h4 class="text-danger text-center">:(</h4>
        <div style="margin: 150px 0"></div>
    <?php endif; ?>
</div>
<?php require(__DIR__ . "/../partials/footer.phtml") ?>
