<?php require(__DIR__ . "/../partials/header.phtml"); ?>

<div class="container section">
    <div class="row">
        <div class="col-md-4">
            <div class="profile-header">
                <h1>Your Profile:</h1>
            </div>
            <div class="profile-menu">
                <div class="menu-item active">Heyyo</div>
                <div class="menu-item">Heyyo</div>
                <div class="menu-item">Heyyo</div>
                <div class="menu-item">Heyyo</div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="menu-display">
                <div class="row">
                    <div class="col-8">
                        <h1 class="profile-name">Nathan Bamford</h1>
                        <p class="aka">aka</p>
                        <h4>Banoulka</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php require(__DIR__ . "/../partials/footer.phtml") ?>
