<?php require(__DIR__ . "/../partials/header.phtml") ?>

<div class="container section">
    <h1 class="title">Create new post</h1>
    <p class="subtext mb-5">Fields marked in * are optional</p>
    <form class="new-post" action="<?= $_SERVER["PHP_SELF"]; ?>" method="POST" enctype="multipart/form-data">
        <div class="row justify-content-around">
            <div class="col-md-7">
                <div class="form-group row align-items-center justify-content-between">
                    <label for="title" class="col-md-4 col-form-label align-self-start py-0">Title:</label>
                    <div class="col-md-8">
                        <input class="form-control" type="text" name="title" id="title" placeholder="What do you want your game to be called?" autocomplete="off" value="<?php if (isset($view->post)) echo $view->post->title; ?>">
                        <p class="chars text-right m-0 pt-1">Character Limit: <span id="title-chars">19</span> Chars</p>
                        <?php if (isset($view->errors["title"])) foreach ($view->errors["title"] as $error) : ?>
                            <p class="text-danger small"><?= $error; ?></p>
                        <?php endforeach; ?>
                    </div>
                </div>

                <div class="form-group row align-items-center justify-content-between">
                    <label for="description" class="col-md-4 col-form-label align-self-start py-0">Description:</label>
                    <div class="col-md-8">
                        <textarea class="form-control" name="desc" id="description" placeholder="Enter a short description about your game"><?php if (isset($view->post)) echo $view->post->description; ?></textarea>
                        <p class="chars text-right m-0 pt-1">Character Limit: <span id="description-chars">220</span> Chars</p>
                        <?php if (isset($view->errors["description"])) foreach ($view->errors["description"] as $error) : ?>
                            <p class="text-danger small"><?= $error; ?></p>
                        <?php endforeach; ?>
                    </div>
                </div>

                <div class="form-group row align-items-center justify-content-between">
                    <div class="col">
                        <label for="content">Main Body:</label>
                        <textarea class="form-control" name="body" id="content" placeholder="This will be the main paragraph for your game post"><?php if (isset($view->post)) echo $view->post->body; ?></textarea>
                        <p class="chars text-right m-0 pt-1">Character Limit: <span id="content-chars">1500</span> Chars</p>
                        <?php if (isset($view->errors["body"])) foreach ($view->errors["body"] as $error) : ?>
                            <p class="text-danger small"><?= $error; ?></p>
                        <?php endforeach; ?>
                    </div>
                </div>

            </div>
            <div class="col-md-5">
                <div class="form-group row align-items-center justify-content-between">
                    <label for="cover-image" class="col-md-5 col-form-label align-self-start py-0 optional">Cover Image:<span class="blue-helper">This will only be viewable to logged in users</span></label>
                    <div class="col-md-7">
                        <p class="form-control file-help">Upload a cover image.</p>
                        <input type="file" class="file-input" name="cover_image" id="cover-image" accept="image/png, image/jpg, image/jpeg">
                        <label for="cover-image" class="file-label">Choose File</label>
                        <small class="text-info ml-2" id="file-name"></small>
                    </div>
                    <?php if (isset($view->errors["Cover Image"])) foreach ($view->errors["Cover Image"] as $error) : ?>
                        <p class="text-danger small ml-3"><?= $error; ?></p>
                    <?php endforeach; ?>
                </div>

                <div class="form-group row align-items-center justify-content-between">
                    <label for="tags" class="col-md-5 col-form-label align-self-start py-0 optional">Tags:<span class="blue-helper">Tags help your game stand out.</span></label>
                    <div class="col-md-7">
                        <div id="tag-list"></div>
                        <select class="custom-select" id="tags">
                            <option selected class="default-tag">Select a tag</option>
                            <?php foreach($view->tags as $tag) : ?>
                                <option value="<?= $tag->title;?>"><?= $tag->title;?></option>
                            <?php endforeach; ?>
                        </select>
                        <?php if (isset($view->errors)) foreach ($view->errors["tags"] as $error) : ?>
                            <p class="text-danger small"><?= $error; ?></p>
                        <?php endforeach; ?>
                        <div>
                        <?php foreach($view->tags as $tag) : ?>
                            <input type="checkbox" name="tags[]" class="hidden" id="<?= $tag->title; ?>" value="<?= $tag->title; ?>">
                        <?php endforeach; ?>
                        </div>
                        <p class="chars text-right m-0 pt-1" id="tag-limit-p">Tag Limit: <span id="tag-limits">4</span> tags</p>
                    </div>
                </div>

                <div class="form-group row align-items-center justify-content-between">
                    <label for="game-state" class="col-md-5 col-form-label align-self-start py-0">Game State:</label>
                    <div class="col-md-7">
                        <select class="custom-select" name="type_stage" id="game-state">
                            <option value="Alpha" class="" selected>Alpha</option>
                            <option value="Beta" class="" selected>Beta</option>
                            <option value="Released" class="" selected>Released</option>
                            <option value="Concept" class="" selected>Concept</option>
                        </select>
                    </div>
                </div>

                <div class="form-group row align-items-center justify-content-between mt-5 pt-5">
                    <div class="col">
                        <button type="submit" name="submit" class="dprim-btn dprim-btn-filled" value="submit">Create Post</button>
                        <a href="../posts/create.php" class="dprim-btn dprim-btn-outline">Reset</a>
                        <button class="ml-5 btn-text" type="button" data-toggle="modal" data-target="#post-preview">Preview Post?</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<div class="modal fade" style="border: 12px solid rgba(71,76,140,0.7);" id="post-preview" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Preview Post</h4>
                <button type="button" class="close" data-dismiss="modal">
                    <span>×</span>
                </button>
            </div>
            <div class="modal-body px-5 pt-3 pb-4">
                <div class="container-section">
                    <div class="post">
                        <div class="row text-center">
                            <div class="col-12">
                                <h3 class="game-state beta"></h3>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-8">
                                <h1 class="game-title">Test Post</h1>
                                <a>
                                    <p class="game-author">Nathan Bamford</p>
                                </a>
                                <div class="price d-flex flex-row align-items-center">
                                    <h5 class="text-danger m-0">£49.99</h5>
                                    <button type="submit" name="buyGame" class="btn btn-success btn-sm ml-3">Buy</button>
                                </div>
                                <p class="game-desc">Description about post Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad deserunt ea exercitationem maxime molestiae nam neque quibusdam quidem veniam voluptatem.</p>
                                <div class="game-body">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aperiam beatae consequatur culpa cumque enim eum inventore ipsam, itaque iure mollitia nesciunt nihil odit officia officiis pariatur porro quae quas quidem sed similique soluta tempora ullam, vero voluptas voluptates, voluptatibus!</p>
                                </div>
                                <div class="game-extras">
                                    <span class="game-tag">4x</span>
                                    <span class="game-tag">Strategy</span>
                                    <span class="game-tag">Con Artist</span>
                                    <span class="game-date">Created 20th March 2019</span>
                                </div>
                                <div class="game-stats">
                                    <p class="game-likes"><i class="far fa-thumbs-up"></i><span class="number">43</span>Like this</p>
                                    <p><i class="fas fa-eye"></i><span class="number">26</span>Watch this</p>
                                    <p><i class="far fa-comment-dots"></i><span class="number">14</span>Comments</p>
                                </div>
                            </div>
                            <div class="col-md-4 d-flex flex-column justify-content-center">
                                <img src="../../uploads/post_covers/no-cover.jpg" alt="Game Artwork" class="artwork">
                                <div class="like-watch-buttons">
                                    <button type="submit" name="watchlistAdd" class="post-btn watch">Watch<i class="ml-2 fas fa-eye"></i></button>
                                    <button type="submit" name="likeAdd" class="post-btn like">Like<i class="ml-3 fas fa-thumbs-up"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", () => {

    });
</script>

<?php require(__DIR__ . "/../partials/footer.phtml") ?>

