<?php require(__DIR__ . "/../partials/header.phtml"); ?>
<?php $post = $view->post; ?>
<div class="container section">
    <?php if($post) : ?>
    <div class="post">
        <div class="row text-center">
            <div class="col-12">
                <h3 class="game-state <?php echo $post->type_stage; ?>"></h3>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <h1 class="game-title"><?php echo $post->title ?></h1>
                <p class="game-author"><?php echo $post->user()->name(); ?></p>
                <p class="game-desc"><?php echo $post->description ?></p>
                <div class="game-body">
                    <p><?php echo $post->body; ?></p>
                </div>
                <div class="game-extras">
                    <?php foreach($view->tags as $tag ) : ?>
                        <span class="game-tag"><?php echo $tag; ?></span>
                    <?php endforeach; ?>
                    <span class="game-date">Created <?php echo date("jS \of F Y H:i", $post->time); ?></span>
                </div>
                <div class="game-stats">
                    <p class="game-likes"><i class="far fa-thumbs-up"></i><span class="number">34</span>Like this</p>
                    <p><i class="fas fa-eye"></i><span class="number">16</span>Watch this</p>
                    <p><i class="far fa-comment-dots"></i><span class="number">3</span>Comments</p>
                </div>
            </div>
            <div class="col-md-4 d-flex flex-column justify-content-center">
                <img src="/img/artwork.png" alt="Game Artwork" class="artwork">
            </div>
        </div>
        <div class="commentannounce">
            <div class="row">
                <div class="col-md-6">
                    <h3>Comments</h3>
                    <div class="comment-box row p-2 m-0 mr-auto">
                        <div class="col-2 d-flex align-items-center justify-content-center pr-0">
                            <img src="/uploads/profile_pictures/profilepic1.png" alt="" class="form-profile">
                        </div>
                        <div class="col-10 d-flex align-items-center pl-0">
                            <form action="#" class="comment-area pl-4">
                                <textarea class="form-control text-area d-flex" name="comment" id="comment" rows="1" placeholder="Leave a comment:"></textarea>
                                <input type="submit" name="submit" class="hidden">
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 text-right">
                    <h3>Announcements</h3>
                    <?php if($view->owner) : ?>
                    <form action="#" method="POST">
                    <div class="announcement-box row p-2 m-0 ml-auto">
                        <div class="col-9 d-flex align-items-center pl-0">
                            <div action="#" class="comment-area pl-4">
                                <textarea class="form-control text-area d-flex" name="announcment" id="announce" rows="1" placeholder="Write Announcement..."></textarea>
                            </div>
                        </div>
                        <div class="col-3 d-flex align-items-center justify-content-center pr-0">
                            <img src="/uploads/profile_pictures/profilepic1.png" alt="" class="form-profile">
                        </div>
                    </div>
                    <input type="submit" name="submit" value="Announce" class="dprim-btn dprim-btn-filled mr-0 mt-2">
                    </form>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <?php else : ?>
        <h1 class="display-3 text-danger text-center">Post not found</h1>
        <h4 class="display-5 text-danger text-center" style="margin-bottom: 200px">This post may have been deleted or be unavailable</h4>
        <h4 class="text-danger text-center">:(</h4>
    <?php endif; ?>
</div>

<?php require(__DIR__ . "/../partials/footer.phtml") ?>
