<?php require(__DIR__ . "/../partials/header.phtml"); ?>
<?php $post = $view->post; if ($post instanceof Post) ?>
<div class="container section">
    <?php if($post) : ?>
    <div class="post">
        <div class="row text-center">
            <div class="col-12">
                <h3 class="game-state <?php echo $post->type_stage; ?>"></h3>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <h1 class="game-title"><?php echo $post->title ?></h1>
                <a href="../../users/view.php?id=<?php echo $post->user()->id; ?>">
                    <p class="game-author"><?php echo $post->user()->name(); ?></p>
                </a>
                <p class="game-desc"><?php echo $post->description ?></p>
                <div class="game-body">
                    <p><?php echo $post->body; ?></p>
                </div>
                <div class="game-extras">
                    <?php foreach($post->tags() as $tag ) : ?>
                        <span class="game-tag"><?php echo $tag->title; ?></span>
                    <?php endforeach; ?>
                    <span class="game-date">Created <?php echo date("jS \of F Y H:i", $post->time); ?></span>
                </div>
                <div class="game-stats">
                    <p class="game-likes"><i class="far fa-thumbs-up"></i><span class="number">34</span>Like this</p>
                    <p><i class="fas fa-eye"></i><span class="number"><?php echo $post->watchCount(); ?></span>Watch this</p>
                    <p><i class="far fa-comment-dots"></i><span class="number">3</span>Comments</p>
                </div>
            </div>
            <div class="col-md-4 d-flex flex-column justify-content-center">
                <img src="../../uploads/post_covers/<?php echo Authentication::isLoggedOn() ? $post->cover_image : "cover-hidden.jpg" ?>" alt="Game Artwork" class="artwork">
                <div class="like-watch-buttons">
                    <?php if (Authentication::isLoggedOn()) : ?>

                        <?php if (Authentication::User()->isOnWatchList($post->id)) : ?>
                            <div class="post-btn disabled">Un-watch<i class="ml-2 fas fa-eye"></i></div>
                        <?php else : ?>
                            <form action="<?php echo $_SERVER["PHP_SELF"]; ?>?post_id=<?php echo $post->id ?>" method="post">
                                <button type="submit" name="watchlistAdd" class="post-btn watch">Watch<i class="ml-2 fas fa-eye"></i></button>
                            </form>
                        <?php endif; ?>


                        <div class="post-btn disabled">Like<i class="ml-2 fas fa-thumbs-up"></i></div>
<!--                        <a href="#" class="post-btn like">Like<i class="ml-3 fas fa-thumbs-up"></i></a>-->
                    <?php else : ?>
                        <div class="post-btn disabled sign">Sign in to like<i class="ml-2 fas fa-thumbs-up"></i></div>
                        <div class="post-btn disabled sign">Sign in to watch<i class="ml-2 fas fa-eye"></i></div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="commentannounce">
            <div class="row">
                <div class="col-md-6">
                    <h3>Comments</h3>
                    <?php if (Authentication::isLoggedOn()) : ?>
                    <div class="comment-box row p-2 m-0 mr-auto">
                        <div class="col-2 d-flex align-items-center justify-content-center pr-0">
                            <img src="/uploads/profile_pictures/<?php echo Authentication::User()->display_pic; ?>" alt="" class="form-profile">
                        </div>
                        <div class="col-10 d-flex align-items-center pl-0">
                            <form action="#" class="comment-area pl-4">
                                <textarea class="form-control text-area d-flex" name="comment" id="comment" rows="1" placeholder="Leave a comment:"></textarea>
                                <input type="submit" name="submit" class="hidden">
                            </form>
                        </div>
                    </div>
                    <?php endif; ?>
                </div>
                <div class="col-md-6 text-right">
                    <h3>Announcements</h3>
                    <?php if(Authentication::isLoggedOn() && $view->owner) : ?>
                    <form action="#" method="POST">
                    <div class="announcement-box row p-2 m-0 ml-auto">
                        <div class="col-9 d-flex align-items-center pl-0">
                            <div action="#" class="comment-area pl-4">
                                <textarea class="form-control text-area d-flex" name="announcment" id="announce" rows="1" placeholder="Write Announcement..."></textarea>
                            </div>
                        </div>
                        <div class="col-3 d-flex align-items-center justify-content-center pr-0">
                            <img src="/uploads/profile_pictures/<?php echo Authentication::User()->display_pic; ?>" alt="" class="form-profile">
                        </div>
                    </div>
                    <input type="submit" name="submit" value="Announce" class="dprim-btn dprim-btn-filled mr-0 mt-2">
                    </form>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <?php else : ?>
        <h1 class="display-3 text-danger text-center">Post not found</h1>
        <h4 class="display-5 text-danger text-center" style="margin-bottom: 200px">This post may have been deleted or be unavailable</h4>
        <h4 class="text-danger text-center">:(</h4>
    <?php endif; ?>
</div>

<?php require(__DIR__ . "/../partials/footer.phtml") ?>
