<?php require(__DIR__ . "/../partials/header.phtml"); ?>
<?php $post = $view->post; if ($post instanceof Post) ?>
<div class="container section" style="background-color: white">
    <?php if($post) : ?>
    <div class="post">
        <div class="row text-center">
            <div class="col-12">
                <h3 class="game-state <?= $post->type_stage; ?>"></h3>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <h1 class="game-title"><?= $post->title ?></h1>
                <a href="../../users/view.php?id=<?= $post->user()->id; ?>">
                    <p class="game-author"><?= $post->user()->name(); ?></p>
                </a>
                <div class="price d-flex flex-row align-items-center">
                    <h5 class="text-danger m-0"><?= Helpers::displayBalance($post->price) ?></h5>
                    <?php if (Authentication::isLoggedOn() && Authentication::User() != $view->owner) : ?>
                    <form method="post" action="<?= $_SERVER["PHP_SELF"] ?>?post_id=<?= $post->id ?>">
                        <button type="submit" name="buyGame" class="btn btn-success btn-sm ml-3">Buy</button>
                    </form>
                    <?php endif; ?>
                </div>
                <p class="game-desc"><?= $post->description ?></p>
                <div class="game-body">
                    <p><?= $post->body; ?></p>
                </div>
                <div class="game-extras">
                    <?php foreach($post->tags() as $tag ) : ?>
                        <span class="game-tag"><?= $tag->title; ?></span>
                    <?php endforeach; ?>
                    <span class="game-date">Created <?= date("jS \of F Y H:i", $post->time); ?></span>
                </div>
                <div class="game-stats">
                    <?php if (Authentication::isLoggedOn() && Authentication::User()->isLiked($post->id)) : ?>
                        <p class="game-likes"><i class="far fa-thumbs-up"></i><span class="number">You and <?= $post->likesCount()-1; ?></span> others like this</p>
                    <?php else : ?>
                        <p class="game-likes"><i class="far fa-thumbs-up"></i><span class="number"><?= $post->likesCount(); ?></span>Like this</p>
                    <?php endif; ?>
                    <p><i class="fas fa-eye"></i><span class="number"><?= $post->watchCount(); ?></span>Watch this</p>
                    <p><i class="far fa-comment-dots"></i><span class="number"><?= $post->commentCount(); ?></span>Comments</p>
                </div>
            </div>
            <div class="col-md-4 d-flex flex-column justify-content-center">
                <img src="<?= Authentication::isLoggedOn() ? $post->cover_image : "../../uploads/post_covers/cover-hidden.jpg" ?>" alt="Game Artwork" class="artwork">
                <div class="like-watch-buttons">
                    <?php if (Authentication::isLoggedOn()) : ?>
                    <form action="<?= $_SERVER["PHP_SELF"]; ?>?post_id=<?= $post->id ?>" method="post">
                        <?php if (Authentication::User() == $view->owner) : ?>
                        <?php elseif (Authentication::User()->isOnWatchList($post->id)) : ?>
                            <button type="submit" name="watchlistRemove" class="post-btn watch reverse"><i class="fas fa-eye-slash"></i></button>
                        <?php else: ?>
                            <button type="submit" name="watchlistAdd" class="post-btn watch">Watch<i class="ml-2 fas fa-eye"></i></button>
                        <?php endif; ?>

                        <?php if (Authentication::User() == $view->owner) : ?>
                            <a href="edit.php?post_id=<?= $post->id ?>" class="btn btn-success text-white mx-1">Edit Post</a>
                        <?php elseif (Authentication::User()->isLiked($post->id)) : ?>
                            <button type="submit" name="likeRemove" class="post-btn like reverse"><i class="fas fa-thumbs-down"></i></button>
                        <?php else : ?>
                            <button type="submit" name="likeAdd" class="post-btn like">Like<i class="ml-3 fas fa-thumbs-up"></i></button>
                        <?php endif; ?>
                    </form>

                    <?php else : ?>
                        <div class="post-btn disabled sign">Sign in to like<i class="ml-2 fas fa-thumbs-up"></i></div>
                        <div class="post-btn disabled sign">Sign in to watch<i class="ml-2 fas fa-eye"></i></div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="commentannounce" id="comments">
            <div class="row">
                <div class="col-md-6">
                    <h3>Comments</h3>
                    <div id="commentbox">

                    </div>
                    <div id="commentList">

                    </div>
                </div>
                <div class="col-md-6 text-right">
                    <h3>Announcements</h3>
                    <div id="announce-list">
                        <?php if(Authentication::isLoggedOn() && $view->owner) : ?>
                            <form action="<?= $_SERVER["PHP_SELF"] ?>?post_id=<?= $post->id; ?>" method="POST">
                                <div class="announcement-box row p-2 m-0 ml-auto">
                                    <div class="col-9 d-flex align-items-center pl-0">
                                        <div class="comment-area pl-4">
                                            <textarea class="form-control text-area d-flex" name="announcement" id="announce" rows="1" placeholder="Write Announcement..."></textarea>
                                        </div>
                                    </div>
                                    <div class="col-3 d-flex align-items-center justify-content-center pr-0">
                                        <img src="<?= Helpers::printIfExternal(Authentication::User()->display_pic); ?>" alt="" class="form-profile">
                                    </div>
                                </div>
                                <input type="submit" name="announcementAdd" value="Announce" class="dprim-btn dprim-btn-filled mr-0 mt-2">
                            </form>
                        <?php endif; ?>

                        <?php foreach ($post->announcements() as $announcement) : ?>
                            <?php if ($announcement instanceof Announcement) : ?>
                                <div class="comment">
                                    <div class="row">
                                        <div class="col-3">
                                            <div class="image">
                                                <img src="<?= Helpers::printIfExternal($post->user()->display_pic) ?>" alt="" class="comment-pic">
                                            </div>
                                        </div>
                                        <div class="col-9">
                                            <div class="commentinfo">
                                                <p class="comment-body"><?= $announcement->body; ?></p>
                                                <div class="extra">
                                                    <span class="time-info ml-auto"><?= Helpers::getTimeSinceMin($announcement->timestamp); ?></span>
                                                    <?php if (Authentication::isLoggedOn() && $view->owner) : ?>
                                                        <form class="ml-3" method="post" action="<?= $_SERVER["PHP_SELF"]; ?>?post_id=<?= $post->id ?>&announcement_id=<?= $announcement->id; ?>">
                                                            <button type="submit" name="announcementDelete" class="btn btn-outline-danger btn-sm">delete</button>
                                                        </form>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endif; endforeach; ?>
                    </div>
                </div>
            </div>
<!--            --><?php //require_once $_SERVER["DOCUMENT_ROOT"] . "/Views/partials/commentAnnouncements.phtml" ?>
        </div>
    </div>
    <?php else : ?>
        <h1 class="display-3 text-danger text-center">Post not found</h1>
        <h4 class="display-5 text-danger text-center" style="margin-bottom: 200px">This post may have been deleted or be unavailable</h4>
        <h4 class="text-danger text-center">:(</h4>
    <?php endif; ?>
</div>

<script>
    document.addEventListener("DOMContentLoaded", async () => {
        let postID = <?= $post->id ?>;
        //let phpSelf = <?//= $_SERVER["PHP_SELF"] ?>//;


        const userRes = await fetch("../requests/auth/me");
        const userJson = await userRes.json();

        const loggedInUser = userJson.user;

        const commentsList = $("#commentList");


        if (loggedInUser) {
            let htmlString =
            `<div class="comment-box row p-2 m-0 mr-auto">
                <div class="col-2 d-flex align-items-center justify-content-center pr-0">
                    <img src="${loggedInUser.display_pic}" alt="" class="form-profile">
                </div>
                <div class="col-10 d-flex align-items-center pl-0">
                    <form action="/posts/view.php?post_id=${ postID }" class="comment-area pl-4" id="commentForm" method="post">
                        <textarea class="form-control text-area d-flex" name="commentBody" id="comment" rows="1" placeholder="Leave a comment:"></textarea>
                        <input type="submit" name="commentAdd" class="hidden" id="commentAdd">
                    </form>
                </div>
            </div>`;
            $("#commentbox").append(htmlString);

            // Add comment eventlistener
            let commentBox = document.getElementById("comment");

            commentBox.addEventListener("keydown", async e => {

               if (e.key === "Enter") {
                   e.preventDefault();
                   if (commentBox.value.trim() !== "") {

                        // Add a new comment
                       let data = {
                           postID,
                           "body": commentBox.value.trim(),
                           "userID": loggedInUser.id
                       };

                       // Remove the old comment box value
                       commentBox.value = "";

                       // Get the new comment data from the server and display it
                       let htmlString = `
                        <div class="comment">
                            <div class="row">
                                <div class="col-3">
                                    <div class="image">
                                        <img src="${loggedInUser.display_pic}" alt="Profile Picture" class="comment-pic">
                                    </div>
                                </div>

                                <div class="col-9">
                                    <div class="commentinfo">
                                        <a href="../../users/view.php?id=${loggedInUser.id}" class="comment-user">${loggedInUser.name}</a>
                                        <p class="comment-body">${data.body}</p>
                                        <div class="extra">
                                            <span class="time-info ml-auto">now</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>`;
                       commentsList.prepend(htmlString);

                       // Send the requests
                       const res = await fetch("../requests/comments/new", {
                           headers: {
                               "Content-Type": "application/json"
                           },
                           method: "POST",
                           body: JSON.stringify(data)
                       });
                       const json = await res.json();
                   }
               }
            });
        }



        await getComments();


        async function getComments() {

            const res = await fetch(`../requests/comments/show/${postID}`);
            const json = await res.json();

            const commentArr = json.comments;

            commentArr.forEach(comment => {
                const { user, body, timestamp } = comment;

                let htmlString = `
                <div class="comment">
                    <div class="row">
                        <div class="col-3">
                            <div class="image">
                                <img src="${user.display_pic}" alt="Profile Picture" class="comment-pic">
                            </div>
                        </div>

                        <div class="col-9">
                            <div class="commentinfo">
                                <a href="../../users/view.php?id=${user.id}" class="comment-user">${user.name}</a>
                                <p class="comment-body">${body}</p>
                                <div class="extra">
                                    <span class="time-info ml-auto">${timestamp}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>`;

                commentsList.append(htmlString);
            });
        }
    });
</script>


<?php require(__DIR__ . "/../partials/footer.phtml") ?>
