<?php require(__DIR__ . "/../partials/header.phtml"); ?>
<?php $post = $view->post; if ($post instanceof Post) ?>
<div class="container section" style="background-color: white">
    <?php if($post) : ?>
    <div class="post">
        <div class="row text-center">
            <div class="col-12">
                <h3 class="game-state <?= $post->type_stage; ?>"></h3>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <h1 class="game-title"><?= $post->title ?></h1>
                <a href="../../users/view.php?id=<?= $post->user()->id; ?>">
                    <p class="game-author"><?= $post->user()->name(); ?></p>
                </a>
                <p class="game-desc"><?= $post->description ?></p>
                <div class="game-body">
                    <p><?= $post->body; ?></p>
                </div>
                <div class="game-extras">
                    <?php foreach($post->tags() as $tag ) : ?>
                        <span class="game-tag"><?= $tag->title; ?></span>
                    <?php endforeach; ?>
                    <span class="game-date">Created <?= date("jS \of F Y H:i", $post->time); ?></span>
                </div>
                <div class="game-stats">
                    <p class="game-likes"><i class="far fa-thumbs-up"></i><span class="number"><?= $post->likesCount(); ?></span>Like this</p>
                    <p><i class="fas fa-eye"></i><span class="number"><?= $post->watchCount(); ?></span>Watch this</p>
                    <p><i class="far fa-comment-dots"></i><span class="number"><?= $post->commentCount(); ?></span>Comments</p>
                </div>
            </div>
            <div class="col-md-4 d-flex flex-column justify-content-center">
                <img src="<?= Authentication::isLoggedOn() ? $post->cover_image : "../../uploads/post_covers/cover-hidden.jpg" ?>" alt="Game Artwork" class="artwork">
                <div class="like-watch-buttons">
                    <?php if (Authentication::isLoggedOn()) : ?>
                    <form action="<?= $_SERVER["PHP_SELF"]; ?>?post_id=<?= $post->id ?>" method="post">
                        <?php if (Authentication::User() == $view->owner) : ?>
                            <div class="post-btn disabled"><i class="fas fa-eye"></i></div>
                        <?php elseif (Authentication::User()->isOnWatchList($post->id)) : ?>
                            <button type="submit" name="watchlistRemove" class="post-btn watch reverse"><i class="fas fa-eye-slash"></i></button>
                        <?php else: ?>
                            <button type="submit" name="watchlistAdd" class="post-btn watch">Watch<i class="ml-2 fas fa-eye"></i></button>
                        <?php endif; ?>

                        <?php if (Authentication::User() == $view->owner) : ?>
                            <div class="post-btn disabled"><i class="fas fa-thumbs-up"></i></div>
                        <?php elseif (Authentication::User()->isLiked($post->id)) : ?>
                            <button type="submit" name="likeRemove" class="post-btn like reverse"><i class="fas fa-thumbs-down"></i></button>
                        <?php else : ?>
                            <button type="submit" name="likeAdd" class="post-btn like">Like<i class="ml-3 fas fa-thumbs-up"></i></button>
                        <?php endif; ?>
                    </form>

                    <?php else : ?>
                        <div class="post-btn disabled sign">Sign in to like<i class="ml-2 fas fa-thumbs-up"></i></div>
                        <div class="post-btn disabled sign">Sign in to watch<i class="ml-2 fas fa-eye"></i></div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="commentannounce" id="comments">
            <?php require_once $_SERVER["DOCUMENT_ROOT"] . "/Views/partials/commentAnnouncements.phtml" ?>
        </div>
    </div>
    <?php else : ?>
        <h1 class="display-3 text-danger text-center">Post not found</h1>
        <h4 class="display-5 text-danger text-center" style="margin-bottom: 200px">This post may have been deleted or be unavailable</h4>
        <h4 class="text-danger text-center">:(</h4>
    <?php endif; ?>
</div>

<?php require(__DIR__ . "/../partials/footer.phtml") ?>
